
spring.datasource.url=jdbc:mysql://localhost:3306/it_asset_management
spring.datasource.username=root
spring.datasource.password=@Vedu#007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
